name: Build extension

on:
  push:
    branches:
      - master
    paths-ignore:
      - web-store-assets/**
      - website/**
  pull_request:
    branches:
      - master
    paths-ignore:
      - web-store-assets/**
      - website/**

jobs:
  build:
    name: Build extension

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install packages
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build extension
        run: yarn build-all
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
